name: CI
on: [push, pull_request]
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y build-essential autoconf automake autoconf-archive libjson-c-dev libglib2.0-dev flex bison libtool cmake libipt-dev libboost-dev

      - name: Setup ld
        run: |
          echo "$PWD/install/lib" | sudo tee -a /etc/ld.so.conf.d/vmtaint.conf
          echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/xen.conf

      - name: Get Xen hash
        id: xenhash
        run: |
          hash=$(git submodule | grep xen | awk '{print $1}')
          echo ::set-output name=hash::$hash

      - uses: actions/cache@v2
        id: xen-cache
        with:
          path: ~/saved-xen
          key: ${{ steps.xenhash.outputs.hash }}

      - name: Compile Xen
        if: steps.xen-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/saved-xen
          git submodule update --init xen
          sudo apt-get install -y libfdt-dev libpixman-1-dev libssl-dev libsdl-dev tightvncserver x11vnc uuid-runtime uuid-dev python3-dev liblzma-dev
          sudo apt-get install -y libc6-dev wget bcc bin86 gawk libpixman-1-dev libaio-dev libfdt-dev nasm
          sudo apt-get install -y libfuse-dev liblzma-dev libsystemd-dev gettext libyajl-dev iasl libbz2-dev e2fslibs-dev ocaml gcc-multilib libpci-dev
          sudo apt-get install -y texinfo texlive-latex-base texlive-latex-recommended texlive-fonts-extra texlive-fonts-recommended
          sudo apt-get install -y markdown pandoc transfig tgif fig2dev ninja-build
          sudo ln -s /usr/include/x86_64-linux-gnu/pci /usr/include/pci
          cd xen
          echo CONFIG_EXPERT=y > xen/.config
          echo CONFIG_MEM_SHARING=y >> xen/.config
          ./configure --disable-pvshim --enable-ovmf --enable-systemd
          make -C xen olddefconfig
          make -j2 dist-xen
          make -j2 dist-tools
          mkdir -p dist/install/etc/ld.so.conf.d
          cp tools/misc/xen-vmtrace dist/install/usr/local/sbin
          echo "/usr/local/lib" > dist/install/etc/ld.so.conf.d/xen.conf
          make -j2 debball
          mkdir -p ~/saved-xen
          mv dist/*.deb ~/saved-xen
          cd ..

      - name: Install Xen
        run: sudo dpkg -i ~/saved-xen/*.deb

      - name: Setup installdir
        run: |
          export INSTALLDIR="$PWD/install"
          mkdir -p $INSTALLDIR/lib/pkgconfig
          mkdir -p $INSTALLDIR/bin
          mkdir -p $INSTALLDIR/include

      - name: Compile and install LibVMI
        run: |
          export INSTALLDIR="$PWD/install"
          git submodule update --init libvmi
          tar czvf libvmi.tar.gz libvmi
          cd libvmi
          autoreconf -vif
          ./configure --disable-kvm --disable-file --disable-bareflank --disable-vmifs --prefix=$INSTALLDIR
          make -j2
          make install
          rm $INSTALLDIR/lib/libvmi.la || :

      - name: Install capstone
        run: |
          export INSTALLDIR="$PWD/install"
          git submodule update --init capstone
          tar czvf capstone.tar.gz capstone
          mkdir -p capstone/build
          cd capstone/build
          cmake ..
          make -j2
          sudo make install
          sudo ldconfig
          cp /usr/local/lib/*capstone* $INSTALLDIR/lib
          cp /usr/local/lib/pkgconfig/*capstone* $INSTALLDIR/lib/pkgconfig
          cp -R /usr/local/include/capstone $INSTALLDIR/include

      - name: Compile and install Triton
        run: |
          export INSTALLDIR="$PWD/install"
          git submodule update --init triton
          tar czvf triton.tar.gz triton
          mkdir -p triton/build
          cd triton/build
          cmake ..
          make -j2
          sudo make install
          cp /usr/local/lib/*triton* $INSTALLDIR/lib
          cp -R /usr/local/include/triton $INSTALLDIR/include

      - name: Compile vmtaint
        run: |
          export INSTALLDIR="$PWD/install"
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INSTALLDIR/lib/
          export PKG_CONFIG_PATH="$INSTALLDIR/lib/pkgconfig/"
          export LDFLAGS="-L$INSTALLDIR/lib"
          autoreconf -vif
          ./configure --prefix=$INSTALLDIR
          make -j2
          make install

      - name: Install dwarf2json
        if: github.ref == 'refs/heads/main'
        run: |
          export INSTALLDIR="$PWD/install"
          git submodule update --init dwarf2json
          tar czvf dwarf2json.tar.gz dwarf2json
          cd dwarf2json
          go build
          cp dwarf2json $INSTALLDIR/bin

      - name: Create archives
        id: archive
        if: github.ref == 'refs/heads/main'
        run: |
          tag=$(git describe --always)
          echo ::set-output name=tag::$tag
          wget https://downloads.xenproject.org/release/xen/4.15.0/xen-4.15.0.tar.gz
          tar czvf source.tar.gz $PWD/*.tar.gz
          SAVEDIR="$PWD/save"
          mkdir -p $SAVEDIR
          mv $PWD/install/* $SAVEDIR
          cp ~/saved-xen/*.deb $SAVEDIR
          cd $SAVEDIR
          tar czvf vmtaint.tar.gz lib bin include *.deb
          mv vmtaint.tar.gz ..

      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.archive.outputs.tag }}
          release_name: Release ${{ steps.archive.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vmtaint.tar.gz
          asset_name: vmtaint.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload Source Asset
        id: upload-source-asset 
        uses: actions/upload-release-asset@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source.tar.gz
          asset_name: source.tar.gz
          asset_content_type: application/tar+gzip

      - name: Delete old release
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 1
          delete_tags: true

